name: Build emuiibo

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  emuiibo:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Mark repo as safe
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Cargo cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          emuiibo/target
        key: emuiibo-${{ runner.os }}-${{ hashFiles('emuiibo/Cargo.lock') }}
        restore-keys: |
          emuiibo-${{ runner.os }}-

    - name: Update packages
      run: |
        sudo -n apt-get update
        sudo -n apt-get install -y git build-essential zip

    - name: Prepare Rust
      uses: moonrepo/setup-rust@v1
      with:
        components: rust-src
        profile: minimal
        cache: false

    - name: Prepare cargo-nx
      run: cargo install cargo-nx --git https://github.com/aarch64-switch-rs/cargo-nx --rev 0dfe4a3c

    - name: Checkout latest libnx commit
      run: |
        git clone --recurse-submodules https://github.com/switchbrew/libnx.git

    - name: Build and install libnx
      run: |
        cd libnx
        make install -j$(nproc)

    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        make emuiibo -j$(nproc)

    - name: Pack ZIP
      run: |
        cd SdOut
        zip -r ../emuiibo.zip .

    - name: Read version from Makefile
      id: get_version
      run: |
        VER_MAJOR=$(grep -oP 'VER_MAJOR\s+:=\s+\K\d+' overlay/Makefile)
        VER_MINOR=$(grep -oP 'VER_MINOR\s+:=\s+\K\d+' overlay/Makefile)
        VER_MICRO=$(grep -oP 'VER_MICRO\s+:=\s+\K\d+' overlay/Makefile)
        FULL_VERSION="$VER_MAJOR.$VER_MINOR.$VER_MICRO"
        echo "full_version=$FULL_VERSION" >> "$GITHUB_OUTPUT"

    - name: Release Tag
      id: reltag
      run: |
        MAKEFILE_VERSION="${{ steps.get_version.outputs.full_version }}"
        if [ "${GITHUB_EVENT_NAME}" = "push" ] && [ "${GITHUB_REF_TYPE}" = "tag" ]; then
          TAG_NAME="${GITHUB_REF_NAME}"
          REL_NAME="emuiibo ${GITHUB_REF_NAME}"
        else
          SHORT_SHA="$(git rev-parse --short HEAD)"
          TAG_NAME="v$MAKEFILE_VERSION-$SHORT_SHA"
          REL_NAME="emuiibo v$MAKEFILE_VERSION ($SHORT_SHA)"
        fi
        echo "tag_name=${TAG_NAME}" >> "$GITHUB_OUTPUT"
        echo "rel_name=${REL_NAME}" >> "$GITHUB_OUTPUT"

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.reltag.outputs.tag_name }}
        name: ${{ steps.reltag.outputs.rel_name }}
        files: emuiibo.zip
        generate_release_notes: true
        prerelease: ${{ github.event_name == 'workflow_dispatch' }}
        token: ${{ secrets.GH_PAT }}
